### PR TITLE
Adds much more devices by checking out alldevices branch from play-store-api repo

### PR DESCRIPTION
**Pull request by petrblaho**
At the time of writing this PR there is an 'alldevices' branch of play-store-api which contains much more devices' properties.
See https://github.com/yeriomin/play-store-api/tree/alldevices/src/main/resources

This PR modifies the fetch_devices.sh script to allow checking out different branch and updates device.properties file.

### CODE REVIEW

**Comment by petrblaho** [comment]
I did not tested imported devices though...

The properties are generated by code from YalpStore - https://github.com/yeriomin/YalpStore/blob/master/app/src/main/java/com/github/yeriomin/yalpstore/bugreport/BugReportDeviceInfoBuilder.java as mentioned in https://github.com/yeriomin/play-store-api/issues/26#issuecomment-416988667 so I assume that these properties are safe for use.

**Comment by petrblaho** [comment]
I tested it with https://github.com/NoMore201/googleplay-api/blob/master/test/test.py

After a lot of failings with configparser I updated fetch_devices.sh script so it ignores some issues with properties files from https://github.com/yeriomin/play-store-api/tree/alldevices/src/main/resources (missing device name, chopped off file, file from forwarded email content :-), etc)

I can log in and run test/test.py with 'bacon' or with 'addison' (the reason I started this :-))

**Comment by NoMore201** [comment]
I think there are a lot of downsides with this:

1. I don't like huge text files, since parsing it increases initialization time, and maintaining it is painful (the only exception is `googleplay_pb2.py`)
2. Too many untested devices

In my opinion we should only introduce tested devices definitions via PR. Moreover we need a way to let the library load a custom device properties file so that people may test new devices without modifying the existing configuration

**Comment by petrblaho** [comment]
I agree with you in both points.

Thanks.

I am closing this now :-)

**Pull request closed without merging**
