### PR TITLE
Fix `libs.googleplay.LoginError: 'server says: UNKNOWN_ERR'`

### PR DESCRIPTION
**Pull request by AhnMo**
There is the solution about this error at https://github.com/NoMore201/googleplay-api/issues/98#issuecomment-555192238 , https://github.com/Ksauder/googleplay-api/commit/792ec362f681b8fe5785590e6f6847729e6fb409

This maybe google changes a login process  unofficially.

### CODE REVIEW

**Comment by TheCapsLock** [comment]
Seems to work here

**Comment by navarasu** [comment]
This works

**Comment by iebb** [comment]
true lifesaver :D

**Comment by simpnu** [comment]
@NoMore201 Would it be possible to have a new version of gpapi released including this fix?
Thanks a lot! :)

**Pull request merged**
