### PR TITLE
Added proxy config for requests

### PR DESCRIPTION
**Pull request by RankoR**

### CODE REVIEW

**Comment by NoMore201** [comment]
Seems ok. I don't get why travis builds are failing, I'll check into that.

**Comment by matlink** [comment]
There are way more modifications than needed for this feature. It breaks the rule of git for atomic commits. It's harder to check what you really modified from what's just a rewriting.

**Comment by matlink** [comment]
@NoMore201 It fails because Travis doesn't pass secured environment variables (cf log):
```Encrypted environment variables have been removed for security reasons.```

**Comment by NoMore201** [comment]
@matlink since it's a feature provided by the requests library, it should be ok by just providing a proxy configuration to the class initializer. Application using the library should take care of the rest. Personally I quite never user proxies, so let us know if something important is missing.

**Comment by matlink** [comment]
@NoMore201 nothing is missing, but I blame that there are more changes than required.
For example reorder of imports: 
https://github.com/NoMore201/googleplay-api/pull/26/files?diff=split#diff-00ac717134705ec18cb5b6bfa9397354L4

**Comment by RankoR** [comment]
@matlink @NoMore201 sorry for reordering, I've accidentally reformatted file in PyCharm while adding this feature.

**Comment by matlink** [comment]
I suggest to edit this PR without reformatting file for better visibility :)

**Comment by NoMore201** [comment]
Once merged IIRC it's not possible to edit/add commits to the PR. I could revert these formatting issues with another commit, if this is what you mean. Otherwise there is something about git/github i still don't know :)

**Comment by matlink** [comment]
Indeed you can't, or you can just revert this commit and add a new one with only needed changes for this feature.
You're the maintainer, that was only for you why I was picky for that.
It's no big deal, if you don't mind keep it as it is.

**Pull request merged**
