### PR TITLE
Add ability to show download progression

### PR DESCRIPTION
**Pull request by matlink**
Signed-off-by: Matlink <matlink@matlink.fr>

### CODE REVIEW

**Comment by NoMore201** [comment]
I think I accidentally removed progress bar in commit e4ccae0, which also re-introduces the `delivery` method. Can you rebase you pull request to latest commit?

**Comment by matlink** [comment]
Should be ok.

**Comment by matlink** [comment]
Also, I'll maybe stick to a given version number with your gpapi because you just broke Gplaycli when you pushed 0.1.4 to pypi :D

**Comment by matlink** [comment]
Don't forget to push it to pypi please :D

**Comment by NoMore201** [comment]
Sorry for the delay, i just noticed PyPi changed backend:
https://pypi.org/

**Pull request merged**
