### PR TITLE
app Listing fix

### PR DESCRIPTION
**Pull request by nolex90**
Based on this comment:
https://github.com/egirault/googleplay-api/issues/48#issuecomment-352294507
I implemented a hotfix for proper listing.
Testing is also implemented.
Some other categories not working well, there are some remaining apps from previous query. For example:
When querying 10 apps the next query with offset 10 only results 4-6 new results.

### CODE REVIEW

**Comment by NoMore201** [comment]
Sorry for the delay. Can you please rebase you commit with latest changes in the `master` branch?
Specifically the last commit c119d1c.

**Comment by nolex90** [comment]
Sure, I'll do it in the next few days.

**Comment by xDragonZ** [comment]
Next few days?

**Comment by bluetrickpt** [comment]
Hello. This fix seems to work fine. Need help merging?

**Comment by nolex90** [comment]
Branch rebased, please do some tests.

**Comment by NoMore201** [comment]
Note that if you revert the commit, personal data will still be in the history, so I suggest to start this PR over from a clean branch based on master

**Pull request closed without merging**
